### ISSUE TITLE
Bug when rendering ![][]

### ISSUE THREAD

**Issue by anhydrous99** [quantizor/markdown-to-jsx#524]
# Description

The following line `![][]` raises a TypeError exception.
```
import Markdown from 'markdown-to-jsx'

<Markdown>![][]</Markdown>
```

Looks like [`refImage`](https://github.com/probablyup/markdown-to-jsx/blob/aedfa137dba1acb94f13a9f09dc3c550a2e869eb/index.tsx#L1660) has no fallback for when the reference doesn't exist while [`refLink`](https://github.com/probablyup/markdown-to-jsx/blob/aedfa137dba1acb94f13a9f09dc3c550a2e869eb/index.tsx#L1681) does.

#### Stack Trace - 
```
TypeError: Cannot read properties of undefined (reading 'B')
    at Object.h (http://localhost:3000/main.8352f82ca6938aad7a39.hot-update.js:815:27)
    at http://localhost:3000/main.8352f82ca6938aad7a39.hot-update.js:991:26
    at t (http://localhost:3000/main.8352f82ca6938aad7a39.hot-update.js:1006:14)
    at t (http://localhost:3000/main.8352f82ca6938aad7a39.hot-update.js:1000:21)
    at q (http://localhost:3000/main.8352f82ca6938aad7a39.hot-update.js:539:15)
    at qt (http://localhost:3000/main.8352f82ca6938aad7a39.hot-update.js:1009:14)
    at __WEBPACK_DEFAULT_EXPORT__ (http://localhost:3000/main.8352f82ca6938aad7a39.hot-update.js:1038:58)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:20018:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:23304:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:24600:20)
```

# Steps to Reproduce

This can be reproduced in the paygroud.

1. Open the official [playgroud](https://probablyup.com/markdown-to-jsx/)
2. copy and paste the following code snippet. `![][]`

Result - 
![Screenshot 2023-10-26 at 1 48 27 PM](https://github.com/probablyup/markdown-to-jsx/assets/11968608/ee69ddda-ee38-4d82-87e8-c3e9d0351d7f)

**Comment by anhydrous99** [comment]
Here is my attempt at fixing this: #525.

**Comment by xyy94813** [comment]
Got same error...

Test case: 

```mdx
[![latest version](https://img.shields.io/npm/v/markdown-to-jsx.svg?label=latest%20%20version)](https://www.npmjs.org/package/markdown-to-jsx)
```

Expected:

[![latest version](https://img.shields.io/npm/v/markdown-to-jsx.svg?label=latest%20%20version)](https://www.npmjs.org/package/markdown-to-jsx)

Actual:

[!\[latest version](https://www.npmjs.org/package/markdown-to-jsx)][(https://www.npmjs.org/package/markdown-to-jsx)](https://www.npmjs.org/package/markdown-to-jsx)
